### ISSUE TITLE
`api/dump` should not be cached

### ISSUE THREAD

**Issue by wei** [xuexb/echo.xuexb.com#1]
`api/dump` provides request specific information and its results, therefore, should not be cached.

Thankfully, real client ips are not included in the page returned (may or may not be working as intended).

**Comment by xuexb** [comment]
hi, 抱歉, @ddhhz 由于我想看`nginx proxy cache`输出的几个`response header`信息, 添加了缓存, 并且没有说明... 我的锅... 刚刚做了以下事情:

1. 添加`expires -1;`让浏览器不缓存
1. `echo.xuexb.com`下不使用`nginx cache`, 单纯的在`/api/cache`接口添加`nginx cache`, 并且加以提示
1. 添加了`https`反向代理说明, 因为在`/api/dump`接口里有些参数还是`http`的

**Comment by wei** [comment]
哈哈谢咯  我又可以免费蹭了
